### ISSUE TITLE
Deprecated config file options

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-integration-test#24]
```
WARN: the option "store.cellbase_cache_size" in configuration files is deprecated since v0.100.0.
WARN: the option "tx_pool.max_verify_cache_size" in configuration files is deprecated since v0.100.0.
WARN: the option "tx_pool.max_conflict_cache_size" in configuration files is deprecated since v0.100.0.
WARN: the option "tx_pool.max_committed_txs_hash_cache_size" in configuration files is deprecated since v0.100.0.
```

**Comment by keroro520** [comment]
These options only exist in [`testdata/config/ckb2019.toml`](https://github.com/nervosnetwork/ckb-integration-test/blob/8bd9cf20d35d7caebe04725b3190bce2ed3d267f/ckb-integration-test/testdata/config/ckb2019/ckb.toml#L85-L87). The `testdata/config/ckb2019.toml` is for nodes running v0.43 or older versions.

You may have passed a v0.100 version binary to `--ckb2019`. I just updated the [README.md](https://github.com/nervosnetwork/ckb-integration-test/blob/fb2f8324dae51c39c7553b1e130cc45d6f419290/ckb-integration-test/README.md#L11-L15), it doesn't require pass `--ckb2019` anymore.
